### ISSUE TITLE
Timestamp usage

### ISSUE THREAD

**Issue by pauliax** [vkonst/ctd-token#1]
OpenZeppelin recommendation:
There’s a problem with using timestamps and now (alias for block.timestamp) for contract logic, based on the fact that miners can perform some manipulation. In general, it’s better not to rely on timestamps for contract logic. The solution is to use block.number instead, and approximate dates with expected block heights and time periods with expected block amounts. Of course, the possibility of manipulation is very low, so this is not a must-implement suggestion, more just like a note to let you know about it.

**Comment by pauliax** [comment]
This issue is no longer relevant as according to the latest OpenZeppelin recommendation:
"The current recommendation is to use timestamps instead. The risk of miner manipulation of timestamps is very low for this use case, and due to the Difficulty Bomb it is now very difficult to correctly estimate future block times. Consider switching to timestamps."
More: https://blog.zeppelin.solutions/global-messaging-token-audit-865e6a821cd8

**Comment by vkonst** [comment]
**Not an issue**

Block times are subject to the following constraints:

- If the stamp of a block is too far in the future, miners will not build on the block (timestamped "in the future")
- The block time cannot be stamped with an earlier time than its parent.

However, a powerful miner to manipulate timestamps over short periods.
A hypothetical small difference between the network time and the "real time" does not jeopardize the campaign in any way.

Thank you for your input.
