### ISSUE TITLE
Constructor sets owner twice

### ISSUE THREAD

**Issue by codingupastorm** [vkonst/ctd-token#4]
Not a massive bug, just going to save you a little gas when you deploy 😉 

You have `owner = msg.sender;` in the constructor for CtdToken, but as CtdToken inherits from Ownable it is already being set.

**Comment by vkonst** [comment]
**Considered as code beautification**
**Code updated**

I duplicated the line in the original code to make it more readable and understandable.
But it may be confusing.

So the line is deleted from the CtdToken constructor.

Thanks for your input.
