### ISSUE TITLE
adjustPhaseBasedOnTime resets phase from AfterIco to MainIco

### ISSUE THREAD

**Issue by temp727** [vkonst/ctd-token#6]
In create(), when now is between icoOpeningTime and closingTime, adjustPhaseBasedOnTime will reset phase to Phases.MainIco even if it was previously AfterIco. computeOversoldAndAdjustPhase will set the phase back, but this allows access to overpaid codepath after the sale ends and could expose other issues.

**Comment by 08xmt** [comment]
This shouldn’t really be a problem, as the create() method becomes uncallable after phase = Phases.AfterIco

**Comment by vkonst** [comment]
**Not an issue**

The create() method call throws an error after phase is set to Phases.AfterIco.
Therefore the phase can not be changed.

Thanks for your input.
