### ISSUE TITLE
function create() redundant checks

### ISSUE THREAD

**Issue by tghdev** [vkonst/ctd-token#9]
The `modifier whenNotClosed` applied to `function create()` requires a Phase != AfterICO. Within the function the `if` statement in Line 119 is therefore redundant, because it is always `true` if the modifier doesn't throw. Hence, the `else` statement in Line 151 will never be triggered.

**Comment by ilejn** [comment]
Phase can be altered by "adjustPhaseBasedOnTime" method.

**Comment by vkonst** [comment]
**Not an issue**

As @ilejn mentioned, the `phase` can be altered by the `adjustPhaseBasedOnTime` method.
Therefore the check is required.

Thank you both for your input.
